version: "3"
services:

  neo4j:
    image: neo4j:4.0.1
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none

  postgres:
    image: postgres:9.6.17-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgweb:
    restart: always
    image: dpage/pgadmin4
    ports:
      - 8081:80
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.org
      - PGADMIN_DEFAULT_PASSWORD=password