version: "3"
services:

  neo4j:
    image: neo4j:4.0.1
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=${NEO_USER}/${NEO_PASSWORD}

  postgres:
    image: postgres:9.6.17-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}