version: "3"
services:

  postgres:
    image: postgres:9.6.17-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgweb:
    restart: always
    image: dpage/pgadmin4
    ports:
      - 8081:80
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.org
      - PGADMIN_DEFAULT_PASSWORD=password